global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['infinity-net-prometheus:9090']

  - job_name: 'GatewayService'
    scrape_interval: 2s
    static_configs:
      - targets: ['localhost:9999']

  - job_name: 'IdentityService'
    scrape_interval: 2s
    static_configs:
      - targets: ['localhost:8282']
