version: "3.9"

services:
  infinity-net-redis:
    image: redis:latest
    container_name: infinity-net-redis
    volumes:
      - infinity-net-redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - infinity-net-network
    restart: unless-stopped

  infinity-net-rabbitmq:
    image: rabbitmq:management-alpine
    container_name: infinity-net-rabbitmq
    command: rabbitmq-server
    environment:
      RABBITMQ_DEFAULT_USER: infinitynetUser
      RABBITMQ_DEFAULT_PASS: Password@123
    volumes:
      - infinity-net-rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "5672:5672" # Port for producer & consumer
      - "15672:15672" # UI dashboard
    networks:
      - infinity-net-network
    restart: unless-stopped

  infinity-net-postgres:
    image: postgres:12.20-bullseye
    container_name: infinity-net-postgres
    environment:
      POSTGRES_USER: infinitynetUser
      POSTGRES_PASSWORD: Password@123
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - infinity-net-postgres-data:/var/lib/postgresql/data
      - ./Docker/postgres/postgres-init-db:/docker-entrypoint-initdb.d:ro
    networks:
      - infinity-net-network
    restart: unless-stopped

  infinity-net-mongodb:
    image: mongo:latest
    container_name: infinity-net-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: infinitynetUser
      MONGO_INITDB_ROOT_PASSWORD: Password@123
    volumes:
      - infinity-net-mongodb-data:/data/db
      - ./Docker/mongodb/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./Docker/mongodb/data:/backup
    ports:
      - "27017:27017"
    networks:
      - infinity-net-network
    restart: unless-stopped

  infinity-net-minio:
    image: minio/minio:RELEASE.2024-08-26T15-33-07Z.fips
    container_name: infinity-net-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - infinity-net-minio-data:/data:r
    environment:
      MINIO_ROOT_USER: infinitynetUser
      MINIO_ROOT_PASSWORD: Password@123
    command: server /data --console-address ":9001"
    networks:
      - infinity-net-network
    restart: unless-stopped

networks:
  infinity-net-network:
    driver: bridge

volumes:
  infinity-net-redis-data:
  infinity-net-rabbitmq-data:
  infinity-net-postgres-data:
  infinity-net-mongodb-data:
  infinity-net-minio-data:
