// <auto-generated />
using System;
using InfinityNetServer.Services.Identity.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfinityNetServer.Services.Identity.Infrastructure.Data.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InfinityNetServer.Services.Identity.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DefaultUserProfile")
                        .HasColumnType("uuid")
                        .HasColumnName("default_user_profile");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("InfinityNetServer.Services.Identity.Domain.Entities.AccountProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("account_providers");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("InfinityNetServer.Services.Identity.Domain.Entities.Verification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("verifications");
                });

            modelBuilder.Entity("InfinityNetServer.Services.Identity.Domain.Entities.FacebookProvider", b =>
                {
                    b.HasBaseType("InfinityNetServer.Services.Identity.Domain.Entities.AccountProvider");

                    b.Property<Guid>("FacebookId")
                        .HasColumnType("uuid")
                        .HasColumnName("facebook_id");

                    b.ToTable("facebook_providers");
                });

            modelBuilder.Entity("InfinityNetServer.Services.Identity.Domain.Entities.GoogleProvider", b =>
                {
                    b.HasBaseType("InfinityNetServer.Services.Identity.Domain.Entities.AccountProvider");

                    b.Property<Guid>("GoogleId")
                        .HasColumnType("uuid")
                        .HasColumnName("google_id");

                    b.ToTable("google_providers");
                });

            modelBuilder.Entity("InfinityNetServer.Services.Identity.Domain.Entities.LocalProvider", b =>
                {
                    b.HasBaseType("InfinityNetServer.Services.Identity.Domain.Entities.AccountProvider");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.ToTable("local_providers");
                });

            modelBuilder.Entity("InfinityNetServer.Services.Identity.Domain.Entities.AccountProvider", b =>
                {
                    b.HasOne("InfinityNetServer.Services.Identity.Domain.Entities.Account", "Account")
                        .WithMany("AccountProviders")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("InfinityNetServer.Services.Identity.Domain.Entities.Verification", b =>
                {
                    b.HasOne("InfinityNetServer.Services.Identity.Domain.Entities.Account", "Account")
                        .WithMany("Verifications")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("InfinityNetServer.Services.Identity.Domain.Entities.FacebookProvider", b =>
                {
                    b.HasOne("InfinityNetServer.Services.Identity.Domain.Entities.AccountProvider", "AccountProvider")
                        .WithOne("FacebookProvider")
                        .HasForeignKey("InfinityNetServer.Services.Identity.Domain.Entities.FacebookProvider", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountProvider");
                });

            modelBuilder.Entity("InfinityNetServer.Services.Identity.Domain.Entities.GoogleProvider", b =>
                {
                    b.HasOne("InfinityNetServer.Services.Identity.Domain.Entities.AccountProvider", "AccountProvider")
                        .WithOne("GoogleProvider")
                        .HasForeignKey("InfinityNetServer.Services.Identity.Domain.Entities.GoogleProvider", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountProvider");
                });

            modelBuilder.Entity("InfinityNetServer.Services.Identity.Domain.Entities.LocalProvider", b =>
                {
                    b.HasOne("InfinityNetServer.Services.Identity.Domain.Entities.AccountProvider", "AccountProvider")
                        .WithOne("LocalProvider")
                        .HasForeignKey("InfinityNetServer.Services.Identity.Domain.Entities.LocalProvider", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountProvider");
                });

            modelBuilder.Entity("InfinityNetServer.Services.Identity.Domain.Entities.Account", b =>
                {
                    b.Navigation("AccountProviders");

                    b.Navigation("Verifications");
                });

            modelBuilder.Entity("InfinityNetServer.Services.Identity.Domain.Entities.AccountProvider", b =>
                {
                    b.Navigation("FacebookProvider");

                    b.Navigation("GoogleProvider");

                    b.Navigation("LocalProvider");
                });
#pragma warning restore 612, 618
        }
    }
}
